# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "altgraph" = super.buildPythonPackage rec {
    pname = "altgraph";
    version = "0.17.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/ba/000a1996d4308bc65120167c21241a3b205464a2e0b58deda26ae8ac21d1/altgraph-0.17.5-py2.py3-none-any.whl";
      sha256 = "15q5c1hnkq2kqr8pq1mbmh0x770m7d7sq81qd00wgc71ph0298pk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "asn1crypto" = super.buildPythonPackage rec {
    pname = "asn1crypto";
    version = "1.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/7f/09065fd9e27da0eda08b4d6897f1c13535066174cc023af248fc2a8d5e5a/asn1crypto-1.5.1-py2.py3-none-any.whl";
      sha256 = "0rzxz1j8bdml3f13b9pbx4cg5271kkql8gdv5j8hi1bjidr40knv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "axmlparserpy" = super.buildPythonPackage rec {
    pname = "axmlparserpy";
    version = "0.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/36/cd1349b022d089f414b373bd86647b67fa5533998f31c5ca9d854895daa0/AxmlParserPY-0.0.4.tar.gz";
      sha256 = "0kvydd52a7iw2kxaskvhpbwyirca5ksdywdkqgdayvm4hqzkk2ng";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2026.5.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/8c/57e832b7af6d7c5abe66eb3fbe3a3a32f4d11ea23a1aa7131371035be991/certifi-2026.5.20-py3-none-any.whl";
      sha256 = "15sqs8m90ip54511731fc0g9xhs9nd56lhv0pspdfjhap84y4liw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docutils" = super.buildPythonPackage rec {
    pname = "docutils";
    version = "0.23";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/91/30151a39f7570f448ed84529390628a651d7f27c87d73c9b887f8189695e/docutils-0.23-py3-none-any.whl";
      sha256 = "1sjz33qmwcq8g129wv3qjhxcarl143sdz4xhnb3w2fzjkfpi7l15";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ecdsa" = super.buildPythonPackage rec {
    pname = "ecdsa";
    version = "0.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/79/119091c98e2bf49e24ed9f3ae69f816d715d2904aefa6a2baa039a2ba0b0/ecdsa-0.19.2-py2.py3-none-any.whl";
      sha256 = "16bkpd9dk3f0q19r4p0qcnm5vy98mp5bk9d7q4v8zikmwg2ms3w4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "8.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/5e/f8e9a1d23b9c20a551a8a02ea3637b4642e22c2626e3a13a9a29cdea99eb/importlib_metadata-8.7.1-py3-none-any.whl";
      sha256 = "0lb12x9kn1j429c9khlbibr4qqsssyav1yqy0yar8j5a3nzq07ss";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "libusb" = super.buildPythonPackage rec {
    pname = "libusb";
    version = "1.0.27.post4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/86/bd57315264483daef8c8dda38109b54e2da0de7a2fe1e06d8bc6a9a78573/libusb-1.0.27.post4-py3-none-any.whl";
      sha256 = "0pkh88w1n8gjxmhacxki9pawpvam7nbbvhssf3xc14i0acdxdcy8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pkg-about"
      self."setuptools"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "26.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/b2/87e62e8c3e2f4b32e5fe99e0b86d576da1312593b39f47d8ceef365e95ed/packaging-26.2-py3-none-any.whl";
      sha256 = "03lqn29hcvc2ff52phpsnqn8dqnf0z47gkhm4kzhfqa4p4v55i2z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pkg-about" = super.buildPythonPackage rec {
    pname = "pkg-about";
    version = "1.2.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/2e/f3b5b00d9bfc9898fb91a40e53ab85019bc81ca2975a10b302fdad91fa0e/pkg_about-1.2.11-py3-none-any.whl";
      sha256 = "0bkbrxpiv76p7zhcv8h3icg3mvrlbxar60jixjm0caj4j481sy38";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."importlib-metadata"
      self."packaging"
      self."setuptools"
      self."tomli"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.17";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz";
      sha256 = "1dkkjri0miidqb1zcqhqljfa34fcy9k5akasgwsv6k622zlk3b0a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycryptodomex" = super.buildPythonPackage rec {
    pname = "pycryptodomex";
    version = "3.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/85/e24bf90972a30b0fcd16c73009add1d7d7cd9140c2498a68252028899e41/pycryptodomex-3.23.0.tar.gz";
      sha256 = "1np4q8rlbf7qchhkqn7hzdi8kj8j42hlxgqakg4jpj0hy1c9g43i";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyinstaller" = super.buildPythonPackage rec {
    pname = "pyinstaller";
    version = "6.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/60/d03d52e6690d4e9caf333dcd14550cde634ce6c118b3bc8fa3112c3186fd/pyinstaller-6.20.0.tar.gz";
      sha256 = "0yil0zn8qq4n6vldpdmy848bp4plkilrq9ggp3gyjqax7phcgicm";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."altgraph"
      self."importlib-metadata"
      self."packaging"
      self."pyinstaller-hooks-contrib"
      self."setuptools"
    ];
  };
  "pyinstaller-hooks-contrib" = super.buildPythonPackage rec {
    pname = "pyinstaller-hooks-contrib";
    version = "2026.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/31/f2d7343d8ed5f7c4678377886f6ce533e6eaaa131b252ce950114c2a7efa/pyinstaller_hooks_contrib-2026.6-py3-none-any.whl";
      sha256 = "1lwxa1lzkzzyrr75jjszvmshn24p1ldd9b7dfl8kcdbb2anbh4zx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
      self."packaging"
    ];
  };
  "pyusb" = super.buildPythonPackage rec {
    pname = "pyusb";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/b8/27e6312e86408a44fe16bd28ee12dd98608b39f7e7e57884a24e8f29b573/pyusb-1.3.1-py3-none-any.whl";
      sha256 = "0c04dafw1nj5agdppl88bhgiba93p717rc62h3z1fixgax2pb6xz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz";
      sha256 = "03qrhk1vz2g12xgy9mdr4p3ibvxprch710gq9kxj5pr16hvj6rnp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tlslite-ng" = super.buildPythonPackage rec {
    pname = "tlslite-ng";
    version = "0.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/fc/3ffc45068af0d088eb8fe3da1b96b4f41049a3a6e583a8f0dc9df48996f9/tlslite_ng-0.8.2-py3-none-any.whl";
      sha256 = "1rcswja90gq9vkzc0x6vsxkzsswprwr4p7df2v5jwylcnid985xw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ecdsa"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7b/61/cceae43728b7de99d9b847560c262873a1f6c98202171fd5ed62640b494b/tomli-2.4.1-py3-none-any.whl";
      sha256 = "1zj9ic1361g962pxrrsasn3nb30zimpnb1nb8gd2488k0ac8318d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.23.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/08/8a/0861bec20485572fbddf3dfba2910e38fe249796cb73ecdeb74e07eeb8d3/zipp-3.23.1-py3-none-any.whl";
      sha256 = "1p24whrmdj7syz6npc7dkdz81i1ckxnxia0bnjf0qw2w1b2rcd8b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
